name: Versioning

on:
    workflow_run:
        workflows: [CI]
        branches: [main]
        types: [completed]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
    contents: write
    pull-requests: write

jobs:
    version:
        name: version bump
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version-file: package.json

            - name: Install dependencies
              run: bun i --frozen-lockfile

            - name: Create Version Pull Request
              uses: changesets/action@v1
              with:
                  version: bun changeset version
                  commit: 'chore: version packages'
                  title: 'chore: version packages'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
